[request_definition]
r = phase, sub, obj, act

[policy_definition]
p = phase, sub, obj, act, eft

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.phase == p.phase && r.sub == p.sub && r.obj == p.obj && r.act == p.act
