services:
  opa:
    image: openpolicyagent/opa:latest
    profiles:
      - opa
    command:
      - run
      - --server
      - --watch
      - --addr=0.0.0.0:8181
      - /policies
    volumes:
      - ./opa/policies:/policies:ro
    networks:
      default:
        aliases:
          - policy-engine
