services:
  opa:
    image: openpolicyagent/opa:latest
    profiles:
      - opa
    command:
      - run
      - --server
      - --watch
      - --addr=0.0.0.0:8181
      - /policies
    volumes:
      - ../policy-engine/opa/policies:/policies:ro
    networks:
      default:
        aliases:
          - policy-engine

  casbin:
    build:
      context: ../policy-engine/casbin
    profiles:
      - casbin
    environment:
      BIND_ADDR: 0.0.0.0:8181
      CASBIN_MODEL_PATH: ./model.conf
      CASBIN_POLICY_PATH: ./policy.csv
    networks:
      default:
        aliases:
          - policy-engine
